; bank $CD  (file $0D0000)

org $CD0000
    incbin "../data/sprites/frame_0079.bin"                        ; 1772 bytes (whole asset)
    incbin "../data/sprites/frame_0080.bin"                        ; 1772 bytes (whole asset)
    incbin "../data/sprites/frame_0081.bin"                        ; 1756 bytes (whole asset)
    incbin "../data/sprites/frame_0082.bin"                        ; 1750 bytes (whole asset)
    incbin "../data/sprites/frame_0083.bin"                        ; 1750 bytes (whole asset)
    incbin "../data/sprites/frame_0084.bin"                        ; 1750 bytes (whole asset)
    incbin "../data/sprites/frame_0085.bin"                        ; 1750 bytes (whole asset)
    incbin "../data/sprites/frame_0086.bin"                        ; 1750 bytes (whole asset)
    incbin "../data/sprites/frame_0087.bin"                        ; 1750 bytes (whole asset)
    incbin "../data/sprites/frame_0088.bin"                        ; 1750 bytes (whole asset)
    incbin "../data/sprites/frame_0089.bin"                        ; 1744 bytes (whole asset)
    incbin "../data/sprites/frame_0090.bin"                        ; 1744 bytes (whole asset)
    incbin "../data/sprites/frame_0091.bin"                        ; 1744 bytes (whole asset)
    incbin "../data/sprites/frame_0092.bin"                        ; 1716 bytes (whole asset)
    incbin "../data/sprites/frame_0093.bin"                        ; 1716 bytes (whole asset)
    incbin "../data/sprites/frame_0094.bin"                        ; 1716 bytes (whole asset)
    incbin "../data/sprites/frame_0095.bin"                        ; 1710 bytes (whole asset)
    incbin "../data/sprites/frame_0096.bin"                        ; 1710 bytes (whole asset)
    incbin "../data/sprites/frame_0097.bin":$0000..$058A        ; 1418 bytes
    incbin "../data/sprites/frame_0097.bin":$058A..$06AE        ; 292 bytes
    incbin "../data/sprites/frame_0098.bin"                        ; 1710 bytes (whole asset)
    incbin "../data/sprites/frame_0099.bin"                        ; 1704 bytes (whole asset)
    incbin "../data/sprites/frame_0100.bin"                        ; 1688 bytes (whole asset)
    incbin "../data/sprites/frame_0101.bin"                        ; 1688 bytes (whole asset)
    incbin "../data/sprites/frame_0102.bin"                        ; 1682 bytes (whole asset)
    incbin "../data/sprites/frame_0103.bin"                        ; 1676 bytes (whole asset)
    incbin "../data/sprites/frame_0104.bin"                        ; 1676 bytes (whole asset)
    incbin "../data/sprites/frame_0105.bin"                        ; 1666 bytes (whole asset)
    incbin "../data/sprites/frame_0106.bin"                        ; 1654 bytes (whole asset)
    incbin "../data/sprites/frame_0107.bin"                        ; 1648 bytes (whole asset)
    incbin "../data/sprites/frame_0108.bin"                        ; 1648 bytes (whole asset)
    incbin "../data/sprites/frame_0109.bin"                        ; 1642 bytes (whole asset)
    incbin "../data/sprites/frame_0110.bin"                        ; 1642 bytes (whole asset)
    incbin "../data/sprites/frame_0111.bin"                        ; 1620 bytes (whole asset)
    incbin "../data/sprites/frame_0112.bin"                        ; 1620 bytes (whole asset)
    incbin "../data/sprites/frame_0113.bin"                        ; 1620 bytes (whole asset)
    incbin "../data/sprites/frame_0114.bin"                        ; 1620 bytes (whole asset)
    incbin "../data/sprites/frame_0115.bin"                        ; 1614 bytes (whole asset)
    incbin "../data/sprites/frame_0116.bin"                        ; 1614 bytes (whole asset)
    incbin "../data/sprites/frame_0117.bin"                        ; 1044 bytes (whole asset)
