; bank $CE  (file $0E0000)

org $CE0000
    incbin "../data/sprites/frame_0118.bin"                        ; 1614 bytes (whole asset)
    incbin "../data/sprites/frame_0119.bin"                        ; 1608 bytes (whole asset)
    incbin "../data/sprites/frame_0120.bin"                        ; 1592 bytes (whole asset)
    incbin "../data/sprites/frame_0121.bin"                        ; 1586 bytes (whole asset)
    incbin "../data/sprites/frame_0122.bin"                        ; 1586 bytes (whole asset)
    incbin "../data/sprites/frame_0123.bin"                        ; 1586 bytes (whole asset)
    incbin "../data/sprites/frame_0124.bin"                        ; 1586 bytes (whole asset)
    incbin "../data/sprites/frame_0125.bin"                        ; 1580 bytes (whole asset)
    incbin "../data/sprites/frame_0126.bin"                        ; 1580 bytes (whole asset)
    incbin "../data/sprites/frame_0127.bin"                        ; 1580 bytes (whole asset)
    incbin "../data/sprites/frame_0128.bin"                        ; 1580 bytes (whole asset)
    incbin "../data/sprites/frame_0129.bin"                        ; 1570 bytes (whole asset)
    incbin "../data/sprites/frame_0130.bin"                        ; 1558 bytes (whole asset)
    incbin "../data/sprites/frame_0131.bin"                        ; 1558 bytes (whole asset)
    incbin "../data/sprites/frame_0132.bin"                        ; 1558 bytes (whole asset)
    incbin "../data/sprites/frame_0133.bin"                        ; 1552 bytes (whole asset)
    incbin "../data/sprites/frame_0134.bin"                        ; 1552 bytes (whole asset)
    incbin "../data/sprites/frame_0135.bin"                        ; 1552 bytes (whole asset)
    incbin "../data/sprites/frame_0136.bin"                        ; 1552 bytes (whole asset)
    incbin "../data/sprites/frame_0137.bin"                        ; 1552 bytes (whole asset)
    incbin "../data/sprites/frame_0138.bin":$0000..$0506        ; 1286 bytes
    incbin "../data/sprites/frame_0138.bin":$0506..$0610        ; 266 bytes
    incbin "../data/sprites/frame_0139.bin"                        ; 1546 bytes (whole asset)
    incbin "../data/maps/level_map_mode3.bin"                        ; 1536 bytes (whole asset)
    incbin "../data/sprites/frame_0140.bin"                        ; 1524 bytes (whole asset)
    incbin "../data/sprites/frame_0141.bin"                        ; 1524 bytes (whole asset)
    incbin "../data/sprites/frame_0142.bin"                        ; 1524 bytes (whole asset)
    incbin "../data/sprites/frame_0143.bin"                        ; 1524 bytes (whole asset)
    incbin "../data/sprites/frame_0144.bin"                        ; 1524 bytes (whole asset)
    incbin "../data/sprites/frame_0145.bin"                        ; 1524 bytes (whole asset)
    incbin "../data/sprites/frame_0146.bin"                        ; 1518 bytes (whole asset)
    incbin "../data/sprites/frame_0147.bin"                        ; 1518 bytes (whole asset)
    incbin "../data/sprites/frame_0148.bin"                        ; 1518 bytes (whole asset)
    incbin "../data/sprites/frame_0149.bin"                        ; 1518 bytes (whole asset)
    incbin "../data/sprites/frame_0150.bin"                        ; 1518 bytes (whole asset)
    incbin "../data/sprites/frame_0151.bin"                        ; 1512 bytes (whole asset)
    incbin "../data/sprites/frame_0152.bin"                        ; 1496 bytes (whole asset)
    incbin "../data/sprites/frame_0153.bin"                        ; 1496 bytes (whole asset)
    incbin "../data/sprites/frame_0154.bin"                        ; 1496 bytes (whole asset)
    incbin "../data/sprites/frame_0155.bin"                        ; 1490 bytes (whole asset)
    incbin "../data/sprites/frame_0156.bin"                        ; 1490 bytes (whole asset)
    incbin "../data/sprites/frame_0157.bin"                        ; 1490 bytes (whole asset)
    incbin "../data/sprites/frame_0158.bin"                        ; 1490 bytes (whole asset)
    incbin "../data/sprites/frame_0159.bin"                        ; 726 bytes (whole asset)
