; bank $DE  (file $1E0000)

org $DE0000
    incbin "../data/sprites/frame_alt_0044.bin"                        ; 1703 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0045.bin"                        ; 1703 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0046.bin"                        ; 1703 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0047.bin"                        ; 1703 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0048.bin"                        ; 1703 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0049.bin"                        ; 1703 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0050.bin"                        ; 1703 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0051.bin"                        ; 1703 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0052.bin"                        ; 1703 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0053.bin"                        ; 1703 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0054.bin"                        ; 1703 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0055.bin"                        ; 1695 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0056.bin"                        ; 1695 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0057.bin"                        ; 1695 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0058.bin"                        ; 1695 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0059.bin"                        ; 1695 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0060.bin"                        ; 1695 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0061.bin"                        ; 1695 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0062.bin"                        ; 1695 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0063.bin":$0000..$01DB        ; 475 bytes
    incbin "../data/sprites/frame_alt_0063.bin":$01DB..$069E        ; 1219 bytes
    incbin "../data/sprites/frame_alt_0064.bin"                        ; 1694 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0065.bin"                        ; 1694 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0066.bin"                        ; 1694 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0067.bin"                        ; 1694 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0068.bin"                        ; 1694 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0069.bin"                        ; 1694 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0070.bin"                        ; 1694 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0071.bin"                        ; 1694 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0072.bin"                        ; 1694 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0073.bin"                        ; 1694 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0074.bin"                        ; 1694 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0075.bin"                        ; 1694 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0076.bin"                        ; 1686 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0077.bin"                        ; 1686 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0078.bin"                        ; 1686 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0079.bin"                        ; 1686 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0080.bin"                        ; 1686 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0081.bin"                        ; 1686 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0117.bin"                        ; 1105 bytes (whole asset)
