; bank $DF  (file $1F0000)

org $DF0000
    incbin "../data/stale/stale_dup_metatiles_mode3.bin"                        ; 4288 bytes (whole asset)
    incbin "../data/stale/stale_dup_metatiles_mode1_tail.bin"                        ; 64 bytes (whole asset)
    incbin "../data/stale/stale_dup_metatiles_mode2b.bin"                        ; 5760 bytes (whole asset)
    incbin "../data/gfx/tiles_unref_1f2780.bin"                        ; 1684 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0082.bin"                        ; 1678 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0083.bin"                        ; 1677 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0084.bin"                        ; 1677 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0085.bin"                        ; 1677 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0086.bin"                        ; 1677 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0087.bin"                        ; 1677 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0088.bin"                        ; 1677 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0089.bin"                        ; 3347 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0090.bin"                        ; 1669 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0091.bin"                        ; 1669 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0092.bin"                        ; 1669 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0093.bin":$0000..$036E        ; 878 bytes
    incbin "../data/sprites/frame_alt_0093.bin":$036E..$0685        ; 791 bytes
    incbin "../data/sprites/frame_alt_0094.bin"                        ; 1669 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0095.bin"                        ; 1669 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0096.bin"                        ; 1668 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0097.bin"                        ; 1668 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0098.bin"                        ; 1668 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0099.bin"                        ; 1668 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0100.bin"                        ; 1668 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0101.bin"                        ; 1668 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0102.bin"                        ; 1668 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0103.bin"                        ; 1668 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0104.bin"                        ; 1668 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0105.bin"                        ; 1668 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0106.bin"                        ; 1668 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0107.bin"                        ; 1668 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0108.bin"                        ; 1668 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0109.bin"                        ; 1668 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0110.bin"                        ; 1668 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0111.bin"                        ; 1668 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0112.bin"                        ; 1668 bytes (whole asset)
    incbin "../data/sprites/sprite_frame_tail.bin"                        ; 283 bytes (whole asset)
