; bank $CC  (file $0C0000)

org $CC0000
    incbin "../data/sprites/frame_0044.bin"                        ; 1846 bytes (whole asset)
    incbin "../data/sprites/frame_0045.bin"                        ; 1846 bytes (whole asset)
    incbin "../data/sprites/frame_0046.bin"                        ; 1846 bytes (whole asset)
    incbin "../data/sprites/frame_0047.bin"                        ; 1846 bytes (whole asset)
    incbin "../data/sprites/frame_0048.bin"                        ; 1846 bytes (whole asset)
    incbin "../data/sprites/frame_0049.bin"                        ; 1846 bytes (whole asset)
    incbin "../data/sprites/frame_0050.bin"                        ; 1846 bytes (whole asset)
    incbin "../data/sprites/frame_0051.bin"                        ; 1840 bytes (whole asset)
    incbin "../data/sprites/frame_0052.bin"                        ; 1840 bytes (whole asset)
    incbin "../data/sprites/frame_0053.bin"                        ; 1840 bytes (whole asset)
    incbin "../data/sprites/frame_0054.bin"                        ; 1824 bytes (whole asset)
    incbin "../data/sprites/frame_0055.bin"                        ; 1812 bytes (whole asset)
    incbin "../data/sprites/frame_0056.bin"                        ; 1812 bytes (whole asset)
    incbin "../data/sprites/frame_0057.bin"                        ; 1812 bytes (whole asset)
    incbin "../data/sprites/frame_0058.bin"                        ; 1812 bytes (whole asset)
    incbin "../data/sprites/frame_0059.bin"                        ; 1812 bytes (whole asset)
    incbin "../data/sprites/frame_0060.bin"                        ; 1812 bytes (whole asset)
    incbin "../data/sprites/frame_0061.bin":$0000..$065E        ; 1630 bytes
    incbin "../data/sprites/frame_0061.bin":$065E..$0714        ; 182 bytes
    incbin "../data/sprites/frame_0062.bin"                        ; 1812 bytes (whole asset)
    incbin "../data/sprites/frame_0063.bin"                        ; 1806 bytes (whole asset)
    incbin "../data/sprites/frame_0064.bin"                        ; 1806 bytes (whole asset)
    incbin "../data/sprites/frame_0065.bin"                        ; 1806 bytes (whole asset)
    incbin "../data/sprites/frame_0066.bin"                        ; 1806 bytes (whole asset)
    incbin "../data/maps/tilemap_mode1_7400.bin"                        ; 1792 bytes (whole asset)
    incbin "../data/maps/tilemap_mode1_7000.bin"                        ; 1792 bytes (whole asset)
    incbin "../data/sprites/frame_0067.bin"                        ; 1790 bytes (whole asset)
    incbin "../data/sprites/frame_0068.bin"                        ; 1778 bytes (whole asset)
    incbin "../data/sprites/frame_0069.bin"                        ; 1778 bytes (whole asset)
    incbin "../data/sprites/frame_0070.bin"                        ; 1778 bytes (whole asset)
    incbin "../data/sprites/frame_0071.bin"                        ; 1772 bytes (whole asset)
    incbin "../data/sprites/frame_0072.bin"                        ; 1772 bytes (whole asset)
    incbin "../data/sprites/frame_0073.bin"                        ; 1772 bytes (whole asset)
    incbin "../data/sprites/frame_0074.bin"                        ; 1772 bytes (whole asset)
    incbin "../data/sprites/frame_0075.bin"                        ; 1772 bytes (whole asset)
    incbin "../data/sprites/frame_0076.bin"                        ; 1772 bytes (whole asset)
    incbin "../data/sprites/frame_0077.bin"                        ; 1772 bytes (whole asset)
    incbin "../data/sprites/frame_0078.bin"                        ; 438 bytes (whole asset)
