; bank $DD  (file $1D0000)

org $DD0000
    incbin "../data/sprites/frame_alt_0007.bin"                        ; 1729 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0008.bin"                        ; 1729 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0009.bin"                        ; 1729 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0010.bin"                        ; 1729 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0011.bin"                        ; 1729 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0012.bin"                        ; 1729 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0013.bin"                        ; 1729 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0014.bin"                        ; 1729 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0015.bin"                        ; 1729 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0016.bin"                        ; 1729 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0017.bin"                        ; 1729 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0018.bin"                        ; 1729 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0019.bin"                        ; 1729 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0020.bin"                        ; 1729 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0021.bin"                        ; 1729 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0022.bin"                        ; 1729 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0023.bin"                        ; 1721 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0024.bin"                        ; 1721 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0025.bin":$0000..$067E        ; 1662 bytes
    incbin "../data/sprites/frame_alt_0025.bin":$067E..$06B9        ; 59 bytes
    incbin "../data/sprites/frame_alt_0026.bin"                        ; 1721 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0027.bin"                        ; 1720 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0028.bin"                        ; 1720 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0029.bin"                        ; 1720 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0030.bin"                        ; 1712 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0031.bin"                        ; 1712 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0032.bin"                        ; 1712 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0033.bin"                        ; 1712 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0034.bin"                        ; 1712 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0035.bin"                        ; 3408 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0036.bin"                        ; 1703 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0037.bin"                        ; 1703 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0038.bin"                        ; 1703 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0039.bin"                        ; 1703 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0040.bin"                        ; 1703 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0041.bin"                        ; 1703 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0042.bin"                        ; 1703 bytes (whole asset)
    incbin "../data/sprites/frame_alt_0043.bin"                        ; 1939 bytes (whole asset)
