; bank $CF  (file $0F0000)

org $CF0000
    incbin "../data/sprites/frame_0160.bin"                        ; 1490 bytes (whole asset)
    incbin "../data/sprites/frame_0161.bin"                        ; 1484 bytes (whole asset)
    incbin "../data/sprites/frame_0162.bin"                        ; 1484 bytes (whole asset)
    incbin "../data/sprites/frame_0163.bin"                        ; 1484 bytes (whole asset)
    incbin "../data/sprites/frame_0164.bin"                        ; 1484 bytes (whole asset)
    incbin "../data/sprites/frame_0165.bin"                        ; 1484 bytes (whole asset)
    incbin "../data/sprites/frame_0166.bin"                        ; 1456 bytes (whole asset)
    incbin "../data/sprites/frame_0167.bin"                        ; 1450 bytes (whole asset)
    incbin "../data/sprites/frame_0168.bin"                        ; 1450 bytes (whole asset)
    incbin "../data/sprites/frame_0169.bin"                        ; 1450 bytes (whole asset)
    incbin "../data/sprites/frame_0170.bin"                        ; 1450 bytes (whole asset)
    incbin "../data/sprites/frame_0171.bin"                        ; 1422 bytes (whole asset)
    incbin "../data/sprites/frame_0172.bin"                        ; 1422 bytes (whole asset)
    incbin "../data/sprites/frame_0173.bin"                        ; 1422 bytes (whole asset)
    incbin "../data/sprites/frame_0174.bin"                        ; 1422 bytes (whole asset)
    incbin "../data/sprites/frame_0175.bin"                        ; 1416 bytes (whole asset)
    incbin "../data/sprites/frame_0176.bin"                        ; 1416 bytes (whole asset)
    incbin "../data/sprites/frame_0177.bin"                        ; 1394 bytes (whole asset)
    incbin "../data/sprites/frame_0178.bin"                        ; 1388 bytes (whole asset)
    incbin "../data/sprites/frame_0179.bin"                        ; 1388 bytes (whole asset)
    incbin "../data/sprites/frame_0180.bin"                        ; 1388 bytes (whole asset)
    incbin "../data/sprites/frame_0181.bin"                        ; 1382 bytes (whole asset)
    incbin "../data/sprites/frame_0182.bin":$0000..$0476        ; 1142 bytes
    incbin "../data/sprites/frame_0182.bin":$0476..$0556        ; 224 bytes
    incbin "../data/sprites/frame_0183.bin"                        ; 1360 bytes (whole asset)
    incbin "../data/sprites/frame_0184.bin"                        ; 1360 bytes (whole asset)
    incbin "../data/sprites/frame_0185.bin"                        ; 1360 bytes (whole asset)
    incbin "../data/sprites/frame_0186.bin"                        ; 1354 bytes (whole asset)
    incbin "../data/sprites/frame_0187.bin"                        ; 1354 bytes (whole asset)
    incbin "../data/sprites/frame_0188.bin"                        ; 1354 bytes (whole asset)
    incbin "../data/sprites/frame_0189.bin"                        ; 1354 bytes (whole asset)
    incbin "../data/sprites/frame_0190.bin"                        ; 1354 bytes (whole asset)
    incbin "../data/sprites/frame_0191.bin"                        ; 1354 bytes (whole asset)
    incbin "../data/sprites/frame_0192.bin"                        ; 1354 bytes (whole asset)
    incbin "../data/sprites/frame_0193.bin"                        ; 1354 bytes (whole asset)
    incbin "../data/sprites/frame_0194.bin"                        ; 1354 bytes (whole asset)
    incbin "../data/sprites/frame_0195.bin"                        ; 1332 bytes (whole asset)
    incbin "../data/sprites/frame_0196.bin"                        ; 1326 bytes (whole asset)
    incbin "../data/sprites/frame_0197.bin"                        ; 1326 bytes (whole asset)
    incbin "../data/sprites/frame_0198.bin"                        ; 1326 bytes (whole asset)
    incbin "../data/sprites/frame_0199.bin"                        ; 1320 bytes (whole asset)
    incbin "../data/sprites/frame_0200.bin"                        ; 1320 bytes (whole asset)
    incbin "../data/sprites/frame_0201.bin"                        ; 1320 bytes (whole asset)
    incbin "../data/sprites/frame_0202.bin"                        ; 1320 bytes (whole asset)
    incbin "../data/sprites/frame_0203.bin"                        ; 1320 bytes (whole asset)
    incbin "../data/sprites/frame_0204.bin"                        ; 1320 bytes (whole asset)
    incbin "../data/sprites/frame_0205.bin"                        ; 1320 bytes (whole asset)
    incbin "../data/sprites/frame_0206.bin"                        ; 1314 bytes (whole asset)
    incbin "../data/sprites/frame_0207.bin"                        ; 414 bytes (whole asset)
